Repository firebase/firebase-functions-python, pull requests merged in 2023-05, with the labels that each got.

#78 refactor(db)!: reference is now instance of a Database reference
  samples/basic_db/functions/main.py
  src/firebase_functions/db_fn.py
Labels: release:stage

#87 chore: Release 0.1.0
  src/firebase_functions/__init__.py
Labels: release:stage, release:publish

#90 chore: Release 0.1.0
  src/firebase_functions/__init__.py
Labels: release:publish
